#!/bin/bash

# This script will install global cargo packages which are defined in
# Dotfiles/backup/cargo file

if cargo install `< ~/Dotfiles/backup/cargo`
  then
    echo "Cargo packages installed successfully."
  else
    echo "There was an error when installing cargo packages."
fi
